### ISSUE TITLE
JSON-LD Link Header should not point to the Core @context

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/context.Orion-LD#10]
but to the Default @context or to the corresponding @context

**Comment by kzangeli** [comment]
Fixed in https://github.com/Fiware/context.Orion-LD/commit/d02ae46513f49634969180c3ddce4e529c60dedc.
Except for one case, where the core context is given literally as context in input payload:
`ngsild_contexts_case_2.test` 
This might not be a problem.
If this issue ever resurfaces, we'll deal with it.
