### ISSUE TITLE
Update operators for attribute values

### ISSUE THREAD

**Issue by PietroGreco** [Fiware/context.Orion-LD#1109]
Hi @kzangeli,

I was looking for this feature which is available in OCB v2: [Update operators for attribute values](https://fiware-orion.readthedocs.io/en/master/user/update_operators.html)

Does Orion-LD offer it? I could not find anything in the documentation
Do you plan to add it?

I needed it in a scenario where race conditions can occur

Thank you in advance,
Pietro

**Comment by kzangeli** [comment]
Nope, sorry, that is not part of the NGSI-LD API.

There is a big problem with it, namely notifications:

What if you update an attribute A1, using e.g. `$inc 5` and you have a subscription with a Q filter `A1 > 12`  ... ?

In order to see whether that subscription is a match (and a notification should be sent), you need to know the current value of the attribute A1 => you need to read the attribute value anyway => new race condition (somebody might modify the value right after your read)

So, by adding this "inc feature" you create another problem that did not exist before.

Anyway, if this feature is ever added to the NGSi-LD API, then Orion-LD will of course implement it.
I'm not going to push for it though (unless you convince me to :))

**Comment by kzangeli** [comment]
Uninteresting issue - closing it
