### ISSUE TITLE
Having id as parameter in a GET /entities request seems to override query arguments

### ISSUE THREAD

**Issue by kiskit** [Fiware/context.Orion-LD#1151]
Hello,

Using 1.0.1.
Given this entity created on orion ld:
```json
        {
		"id": "uri:t1",
		"type": "Temperature",
		"dataProvider": {
			"type": "Property",
			"value": "62349895462c09197b1d6776"
		},
		"scope": {
			"type": "Property",
			"value": "/Madrid"

		},
		"xy": {
			"type": "Property",
			"value": "some value"
		}
	}
```

1. A GET on /entities?q=scope=="/Madrid" returns the entity.
2. A GET on /entities?q=scope=="/Paris" doesn't return the entity.
3. A GET on /entities?id=uri:t1&q=scope=="/Paris" returns the entity.

I would think the query filters out the entity from the results. It may be expected behavior but then I'm not sure why. With type instead of id, 3 would not return the entity.

**Comment by kzangeli** [comment]
Hello there,
yeah, I just discovered (just a few days ago) that a design decision I took quite some time ago (2 years ago?) wasn't too fortunate:
Whenever you do a `GET /entities` with `?id=X` and there's just one single entity id in X (could be a comma-separated list), then I translate the request into a `GET /entities/X` - which is a different service routine, AND it does not support the 'q' parameter - it is ignored.
That's why you see what you see. I'll fix it.

I had my reason for this "peculiarity" - namely ` GET /entities/{entityId}` supports forwarding while `GET /entities` does not.
BUT, it was a mistake and I'll remove the "feature".

Thank you for reporting!

BTW, funny you're using scope as a Property - we've already added the NGSI-LD Scope in the API spec, it just hasn't been implemented in Orion-LD yet.  So, be careful, once I implement NGSI-LD scope, your current scopes will be problematic ...
I imagine you tried to mimic the NGSIv2 Service-Path and just happened to pick the very same name we decided to use for NGSI-LD.
Once scopes are implemented, the broker will expect a JSON string as RHS of "scope", and not a JSON object, so, that will be a little problematic. Would you consider changing to "Scope" ?   To avoid future problems?

**Comment by kiskit** [comment]
Thanks for your reply. We work for Orange and we're using scope as the standard implies or at least in that spirit. By the way if you're interested we've used an antlr grammar for it, so that its implementation always conforms to the standard (ABNF translates pretty well into antlr).
It can be used for queries too. I can share if you're interested. We've got a C++ example we've done for fun that does scope analysis and tells you if it matches other scopes.

**Comment by kzangeli** [comment]
ok ... while that might work for you, in Orion's database you will have entities with properties called "scope" and that is an attribute.
If not ... I can't see how this would possible work.
And, when Orion-LD implements "scope" finally (probably not this year), we're gonna have problems.
We can meet if you want and I explain why exactly this is a problem.

**Comment by papr8ka** [comment]
Hi,

I'm commenting this as I'm working with @kiskit. On our side, the scope property is mandatory to provide access control. As it is not available for now in Orion, we're developping a proxy that provides a scope verification through an header. This is not something that is here to last, as it will disappear as soon as Orion ld implements scopes. @kiskit developped a scope parser using antlr that can understand the etsi spec scope grammar. For now, as scope is not a special ngsi field in orion, we have no other choice to use the classic { "type": "Property", "value": "/"ourScope }, but it is not a problem to change it afterward.

Quick example, get entity, where port `1028` is the proxy:

```bash
curl --request GET \
  --url 'http://127.0.0.1:1028/entities/uri:t1' \
  --header 'X-Scope-Q: /Bangkok/Sukhumvit/Soi_24,(/Paris;/Soho)'
```

The proxy will parse the X-Scope-Q header using antlr. It will then transform it into q filter to add to the request made to orion, so we get something like

```bash
curl --request GET \
  --url 'http://127.0.0.1:1026/ngsi-ld/v1/entities?id=uri%3Aentity11&q=(scope=="/Bangkok/Sukhumvit/Soi_24"|(scope=="/Paris";Bscope=="/Soho"))
```

This is why we opened this issue related to the q. And we can share the code to parse an entity scope, but also a scope passed in header with AND/OR conditions using [antlr](https://github.com/antlr/antlr4).

**Comment by kzangeli** [comment]
ok, as long as you are aware of the problem ... no problem.

**Comment by kzangeli** [comment]
I'll try to fix this issue asap - hopefully I have some time today even,
but meanwhile, as a workaround,
just add a second entity id (one that does not exist) to the query - that way you avoid for Orion-LD to use the simpler service routine:
```
GET /entities?id=uri:t1,uri:notAnEntity&q=scope=="/Paris"
```

**Comment by kiskit** [comment]
Great suggestion, thanks

**Comment by kzangeli** [comment]
Fixed it - workaround no longer needed.
But guys ... don't use "latest" - it's dangerous - pick the tag of this latest and use the tag instead.
Otherwise, I might implement something new, break something old, and your stuff stops working.
Yes, I run plenty of tests before merging anything, but, it's simply not possible to cover 100%, especially not in such a generic thing as Orion-LD.

**Comment by kiskit** [comment]
Super efficient, thanks. We'll be using "official" tags only so for now we'll do with 1.0.1 and the trick you gave us. Once you tag a 1.0.2 or something like that we'll switch to it and remove the patch.

**Comment by kzangeli** [comment]
ok!
Next release (v1.1) is planned for end of July.
Closing the issue.
