### ISSUE TITLE
Getting 'No such tenant' when starting from scratch

### ISSUE THREAD

**Issue by pdmangel2** [Fiware/context.Orion-LD#1228]
When starting from scratch (empty database), our nodejs application gets following exception when querying for entities:
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/NonExistingTenant",
    "title": "No such tenant",
    "detail": "Tenant01"
}
The query is done at application startup.

I encountered this with orion-ld version 1.0.1, but also with 1.1.0

This looks like issue #948, which should be fixed.

**Comment by kzangeli** [comment]
Not exactly the same as issue #948.
You see, tenants are in the end mongo databases.
They are created on demand, just create an entity on any tenant and the database for the tenant will be created, automatically.

Queries on the other hand, as they aren't creating anything, no tenant will be created.
Sending a query on a tenant that does not exist makes very little sense, and it is probably a mistake,
so, we opted for responding with an error instead of an empty array (in ETSI ISG CIM, where thre NGSI-LD API is designed).

This is just the broker doing what it is supposed to do.
