### ISSUE TITLE
Path in context file not transformed properly

### ISSUE THREAD

**Issue by SBlechmann** [Fiware/context.Orion-LD#1260]
Hey there,

I'm using orionld version 1.1.1 and found a small bug while trying to patch an attribute.

In my context file, I have defined my prefix like this:
"myOntology": "https://<myontology.org/schema/"
"myAttr": "myOntology:myAttr"

When I run a Patch towards http://{{orion}}/ngsi-ld/v1/entities/<myEntity>/attrs/<myAttr> I get the following repsonse
```
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/ResourceNotFound",
    "title": "Entity/Attribute not found",
    "detail": "Entity 'myEntity', Attribute 'myAttr' (https://myOntology=org/schema/myAttr)"
}
```
So the url is not transformed back properly at this endpoint.

When I hit the request against http://{{orion}}/ngsi-ld/v1/entities/<myEntity>/attrs (and adapting the body so that the attribute should get changed properly), the URL gets in fact transformed correctly.

I'm still facing a different error from the used ontology, but at least the url is transformed properly to https://myOntology.org/schema/myAttr

Edit: Seems to just be a wrong print in the error message then.

Thanks for looking into this :)

**Comment by kzangeli** [comment]
Yeah, we discussed this.
The change from dot to equal sign is mandatory before storing keys in mongo (well, dots are prohibited).
So, seems like I messed up and used the "mongo transformed" variable instead of the "original value" variable in the error message.
Not very high on my ToDo but yes, I'll fix it.
Bad errors in the log file is only confusing ...

Thanks for reporting!

**Comment by kzangeli** [comment]
Hopefully fixed the issue in PR https://github.com/FIWARE/context.Orion-LD/pull/1302
