### ISSUE TITLE
Create an MQTTS subscription using the V1

### ISSUE THREAD

**Issue by ColoDidac** [Fiware/context.Orion-LD#1270]
Trying to create an MQTTS subscription using the V1 with ngsi-ld/v1. The subscription returns an "Unable to connect to MQTT server" statement.
It's possible to create an MQTTS subscription for the credentials or just plain MQTT?
Thanks!!

**Comment by kzangeli** [comment]
Notification over MQTT go via an MQTT server/broker.
In my functional tests I use mosquitto, but any MQTT broker should work.
I guess that's what's missing for you, you haven't started any MQTT broker alongside Orion-LD.

I haven't implemented mqtts yet, only mqtt. Sorry ...

For hints, take a look at this [functest](https://github.com/FIWARE/context.Orion-LD/blob/develop/test/functionalTest/cases/0000_ngsild/ngsild_subscription_with_mqtt_notifications.test)

If you need help, just shout!

Wait, your problem is probably only that Orion-LD doesn't support MQTTS, and there isn't a clear error message about it ...

**Comment by ColoDidac** [comment]
Thank you so much for the response,
Yes, I think that was my problem.
I will search for some alternative way.
Do you suggest any way to put credentials in a subscription?
Thank you!

**Comment by tonyrosset** [comment]
i am using MQTT and still facing the same problem "Unable to connect to MQTT server"

**Comment by kzangeli** [comment]
Yes, mqtts is not supported.
I'll get to that, some day ...  A lot on my plate right now, sorry!
