### ISSUE TITLE
Create more informative logs

### ISSUE THREAD

**Issue by FR-ADDIX** [Fiware/context.Orion-LD#1312]
Is it possible to see in the log level "Error" also the triggering entity?

`time=Wednesday 25 Jan 10:13:59 2023.173Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionldError.cpp[65]:orionldError | msg=***** ERROR null is not allowed as RHS in a JSON-LD document: value (status code: 400)`

Or do I have to set another log level for it?

**Comment by kzangeli** [comment]
Sorry, that's not part of the implementation right now.
I admit the error handling and logging could be greatly improved.
However, for this particular error, it seems like you have a `null` as right-hand-side somewhere.
Should be quite easy to find (assuming you have the payload body)

**Comment by FR-ADDIX** [comment]
Well, what here for an error occurs is already clear to recognize, but if this would be only an import and if the data would come then also still beautifully slowly one after the other.

At the moment there are about 7-9 processes importing data.
There are 200 - 300 imports per second.
4 or 5 of the imports are done by myself, the others are delivered externally.
If one could at least recognize the triggering entity, that would already point the way.

**Comment by kzangeli** [comment]
Yeah, I agree.
I could easily (I think! :)) add more info (entity id, attr name, sub attr name, etc) in the log. For this specific error!

**Comment by kzangeli** [comment]
So, finally got some time to look into this issue.
Weekends are blessed! :)
Just me and my PC, no interruptions (well, my boss sometimes ... :))

Hope I fixed it, in PR #1314.
Test your stuff again, with the newest tag from dockerhub (if all goes well, it should be pushed in about 30 min) and if you're satisfied, please close this issue.

_[ Due to the changes in error handling, I got a few errors in functests. Will take a bit longer than 30 min ]_

**Comment by FR-ADDIX** [comment]
works fine
