### ISSUE TITLE
error Missing value/object/languageMap field for Attribute at creation time

### ISSUE THREAD

**Issue by pdmangel2** [Fiware/context.Orion-LD#1564]
When trying to create an entity in **simplified format** (see below), we get a 400 - Bad Request

```
{
  "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
  "title": "Missing value/object/languageMap field for Attribute at creation time",
  "detail": "https://uri.etsi.org/ngsi-ld/default-context/address"
}
```

```
POST http://orion:1026/ngsi-ld/v1/entities
Content-Type: application/json
NGSILD-Tenant: t_02

{
    "gsApplicationType": {
        "type": "Property",
        "value": "Device"
    },
    "name": "device-9845C",
    "batteryLevel": 0.65,
    "deviceCategory": [
        "Sensor"
    ],
    "deviceState": "absent",
    "firmwareVersion": "v23.5",
    "location": {
        "type": "Point",
        "coordinates": [
            3.5665602547332065,
            50.99141938196186
        ]
    },
    "configuration": [
        {
            "parameter": "batteryType",
            "value": "AA"
        }
    ],
    "address": {
        "streetAddress": "Pohjoisesplanadi 11-13 ",
        "addressLocality": "Helsinki",
        "addressRegion": "Helsinki",
        "addressCountry": "Finland",
        "postalCode": "00099",
        "postOfficeBoxNumber": "1"
    },
    "dateCreated": "2024-02-22T09:10:19.226Z",
    "dateModified": "2024-02-22T09:10:19.226Z",
    "id": "urn:ngsi-ld:Device:device-9845C",
    "type": "Device"
}
```

**Comment by kzangeli** [comment]
Yes, I believe that's how it's supposed to work.
It's the way I understood it anyway.

I'll go back take a look at the NGSI-LD API spec and especially consult with my colleagues in ETSI ISG CIM.
Might be I've misunderstood.

You see, when the RHS is a Number, a Boolean, it's straightforward, must be a Property.
BUT, when an object, it's not so clear.
If the object has a `type` and a `coordinates` field, it's understood as a GeoProperty.
In all other cases (if object), a little more is needed for the broker to guess the attribute type.

That said, might be I've misunderstood ...
I'll let you know, in this very issue, as soon as I find out more.

**Comment by kzangeli** [comment]
So, we had a long discussion about this and I'm afraid I was right.
It's not allowed.
The reason is that it's too easy to "get things wrong".
The way I personally see this is that "You might not know what you're doing, so, just to be sure, we will not allow this".

I tried to change the way it's specified to let you do what you are trying to do, using the URL param "?format=simplified", but, I got shot down there as well.
So, sorry, you need to put the "value" keyword in there, e.g.:
```
   ...
    "address": {
        "value": {
            "streetAddress": "Pohjoisesplanadi 11-13 ",
            "addressLocality": "Helsinki",
            "addressRegion": "Helsinki",
            "addressCountry": "Finland",
            "postalCode": "00099",
            "postOfficeBoxNumber": "1"
        }
    },
    ...
```

**Comment by kzangeli** [comment]
That said ...
If you REALLY need the broker to work that way, I could implement an exception.
I don't encourage doing that though, as depending on a special case would completely tie you into using a specific implementation of the NGSI-LD context broker.
Depending on a special fix, you could never change the broker for another implementation, like Scorpio or Stellio.

The fix is very simple, just allow it and create the attribute as a Property IF "?format=simplified" is in use.
I'd probably have to invent some HTTP header as well, to turn on this special treatment.
Cause if I don't, then Orion-LD would not behave the way it should in NGSI-LD conformance tests.

So, is this what you want?

**Comment by jason-fox** [comment]
In **concise format** an attribute like:

```json
"temperature": {
  "value": 100,
  "unitCode": "CEL",
  "accuracy": 100
}
```

expands to include _Properties of Properties_ as shown:

```json
"temperature": {
  "type" : "Property"
  "value": 100,
  "unitCode": "CEL",
  "accuracy": {
    "type" : "Property",
    "value": 100
  }
}
```

how would you expect this **simplified format**  payload to expand If it doesn't thrown an error,?

```json
"temperature": {
  "value": 100,
  "unitCode": "CEL",
  "accuracy": 100
},
```

it is ambiguous, should it be _Properties of Properties_


```json
"temperature": {
  "type" : "Property"
  "value": 100,
  "unitCode": "CEL",
  "accuracy": {
    "type" : "Property",
    "value": 100
  }
}
```

or **value** as JSON Object?


```json
"temperature": {
  "type" : "Property"
  "value": {
    "value": 100,
    "unitCode": "CEL",
    "accuracy": 100
  }
}
```

Or even **json** as raw JSON?

```json
"temperature": {
  "type" : "JsonProperty"
  "json": {
    "value": 100,
    "unitCode": "CEL",
    "accuracy": 100
  }
}
```

**Comment by pdmangel2** [comment]
Ken, we can deal with providing the address info as address->value. No need to change.
How about links to other entities (e.g. a deviceRef) ... these are supposed to be provided as 'object' instead of 'value' ?

**Comment by kzangeli** [comment]
> How about links to other entities (e.g. a deviceRef) ... these are supposed to be provided as 'object' instead of 'value' ?

Yes, that sounds very much like a `Relationship` attribute, and those have an `object` and not a `value`.

**Comment by kzangeli** [comment]
So, if this issue is resolved, please go ahead and close it.
(I prefer not to close issues myself, unless I opened it personally. Better if the issuer closes, to acknowledge there are no more doubts/problems)
