### ISSUE TITLE
/version Endpoint breaks compatablity with existing NGSIv2 clients

### ISSUE THREAD

**Issue by stv0g** [Fiware/context.Orion-LD#411]
Can we somehow have a response for the `/version` endpoint which is both parsable by NGSIv2 and NGSI-LD clients?

e.g. 

```json
{
  "compliance": [ "ngsi-ld" ],
  "version": "post-v0.1.0",
  [...]
}
```

**Comment by kzangeli** [comment]
The problem is that NGSIv2 `/version` uses the field `version` and for NGSI-LD this is not enough.
In NGSi-LD we need two different versions.
One that specifies the version of the NGSIv2 part and the other that specifies the version of the NGSI-LD part.

What I did was to change the name of the old "version" to be "orion version" and I added a new field called "orionld version".

Parsable it is, as it is correct JSON. Your problem is probably that you want to use the "version" field and in the NGSI-LD response there isn't one.

Couldn't you simply check for existence of the "version" field?
If not present, it's Orion-LD.

**Comment by stv0g** [comment]
> Couldn't you simply check for existence of the "version" field? If not present, it's Orion-LD.

I agree we can do it.

Does NGSI-LD specify any level of compatibility with NGSIv2?

**Comment by kzangeli** [comment]
Yes, there is a whole lot of compatibility between NGSIv2 and NGSI-LD. As much as I have been able to maintain.
The very same database is used for entities created with NGSIv2 as with NGSI-LD.

This means that you can create an entity using NGSI-LD and you can later retrieve that same entity using NGSIv2 calls.
Orion-LD is an Orion that *also* implements NGSI-LD.

However, Orion isn't aware of the @context. This makes the two APIs pretty different.
For example, if you create an entity using NGSI-LD and that entity has an attribute (Property) called P1, and the context of that request defines P1 to "http://my.context/props/P1", when you later retrieve the entity using NGSIv2, you won't see P1 as "P1", but as its *long-name* "http://my.context/props/P1", because the long name is the real name of the attribute (property).

There are many, many differences between NGSIv2 and NGSI-LD but I have done everything possible to make it as compatible as possible.
