### ISSUE TITLE
Error 411: Length required

### ISSUE THREAD

**Issue by YannickLecroart** [Fiware/context.Orion-LD#695]
Hi,

I have created an API via the WSO2 API Manager curl GET requets work fine as you can see below:

![image](https://user-images.githubusercontent.com/43994829/105514802-39f34b00-5cd4-11eb-8fe6-e938693cfe69.png)

But when trying to setup a POST request I get the following message "error 411: Length required"

![image](https://user-images.githubusercontent.com/43994829/105515222-b8e88380-5cd4-11eb-9cc0-e6ff6bdacd3d.png)

I have tried different things such as disabling chunking or forcing content length header (as WSO2 removes that header by default) by changing the sequence file as shown below but to no avail:

![image](https://user-images.githubusercontent.com/43994829/105515626-33190800-5cd5-11eb-8193-e2c840ab1b57.png)

And what is strange is that I use command prompt to make the same post request it works even I do not specifiy the content-length header which suggest that it is added automatically (correct me if I am wrong):

![image](https://user-images.githubusercontent.com/43994829/105516175-da963a80-5cd5-11eb-9166-ea73bd01a942.png)

There must be something I am doing wrong could you please help me out?

Thanks in advance.

Regards,

**Comment by kzangeli** [comment]
Hi, not sure what is happening with your application, but from what you are describing, it seems like it doesn't send a correct Content-Length HTTP header - which is mandatory in any request that carries a payload body.
Without it, the broker doesn't know where one request ends and the next one begins.
And yes, most commands like curl, adds the Content-Length automatically.
You simply need to find a way to fix that "little" problem and all will be good.

From one of the screenshots I see something weird ... `-H "Content-Length: aux"` ... what is that?

Remove that - it will only sabotage the content length, as instead of an automatic real value ("150" for example) - the string "aux" will be the value. The broker will try to convert the string "aux" into an integer and 0 will be the result - which is of course not a valid value - hence the error.

So, in case that "Content-Length: aux" is somehow part of your application, I'd suggest to remove it.
If your application is using curl, the Content-Length will be set according to the length of your payload body - automatically.
 
Good luck!

**Comment by YannickLecroart** [comment]
I was able to resolve that issue by using the following custom mediation sequence:

```
<sequence xmlns="http://ws.apache.org/ns/synapse" name="contentLengthadd">
		<property name="COPY_CONTENT_LENGTH_FROM_INCOMING" value="true" scope="axis2"/>
		<property name="FORCE_HTTP_CONTENT_LENGTH" scope="axis2" value="true"/>
</sequence>
```

Thanks your time anyway!
