### ISSUE TITLE
Response of POST /ngsi-ld/v1/entityOperations/upsert is corrupted when no entities exist

### ISSUE THREAD

**Issue by fisuda** [Fiware/context.Orion-LD#885]
The Response body of POST /ngsi-ld/v1/entityOperations/upsert is corrupted when no entities exist.

```
HTTP/1.1 201 Created
Connection: Keep-Alive
Content-Length: 55
Content-Type: application/ld+json
Date: Mon, 07 Jun 2021 09:59:47 GMT

["{
```

The following is a script to reproduce it.

```
#!/bin/sh
curl -iX POST 'http://localhost:1026/ngsi-ld/v1/entityOperations/upsert' \
-H 'Content-Type: application/json' \
-H 'Link: <https://context.lab.letsfiware.jp/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json' \
--data-raw '[
 {"id": "urn:ngsi-ld:TemperatureSensor:001", "type": "TemperatureSensor", "temperature": { "type": "Property", "value": 21, "unitCode": "CEL" } },
 {"id": "urn:ngsi-ld:TemperatureSensor:002", "type": "TemperatureSensor", "temperature": { "type": "Property", "value": 21, "unitCode": "CEL" } },
 {"id": "urn:ngsi-ld:TemperatureSensor:003", "type": "TemperatureSensor", "temperature": { "type": "Property", "value": 21, "unitCode": "CEL" } },
 {"id": "urn:ngsi-ld:TemperatureSensor:004", "type": "TemperatureSensor", "temperature": { "type": "Property", "value": 21, "unitCode": "CEL" } },
 {"id": "urn:ngsi-ld:TemperatureSensor:005", "type": "TemperatureSensor", "temperature": { "type": "Property", "value": 21, "unitCode": "CEL" } },
 {"id": "urn:ngsi-ld:TemperatureSensor:006", "type": "TemperatureSensor", "temperature": { "type": "Property", "value": 21, "unitCode": "CEL" } }
]'
```

- Orion-ld version info

```
{
  "orionld version": "0.8.1",
  "orion version":   "1.15.0-next",
  "uptime":          "0 d, 0 h, 6 m, 28 s",
  "git_hash":        "nogitversion",
  "compile_time":    "Sun Jun 6 08:13:51 UTC 2021",
  "compiled_by":     "root",
  "compiled_in":     "buildkitsandbox",
  "release_date":    "Sun Jun 6 08:13:51 UTC 2021",
  "doc":             "https://fiware-orion.readthedocs.org/en/master/"
}
```

```
$ docker images
fiware/orion-ld                           v0.8.1                         aa7f12f3a154   26 hours ago
```

**Comment by kzangeli** [comment]
ok!
I will get right on that!
Thanks for reporting!!! :)

**Comment by kzangeli** [comment]
The request works just fine if you "Accept: application/json", instead of ld+json ...
I'm gonna have to do something about this, of course, not 100% sure *what* as of right now.
The response payload body is an array of strings, the entity-ids, and, I don't see how I can fit the @context inside there.
Actually, the @context shouldn't be there, as there is no expansion in the body - it would be completely useless to include it.
Probably the best solution is to just ignore ld+json ans respond just as for "application/json".

I need to consult with my colleagues in ETSI ISG CIM.

For now, just don't ask for ld+json in your Accept header - it makes no sense

**Comment by fisuda** [comment]
Thank you for your quick reply. I understand.

**Comment by kzangeli** [comment]
Fixed in here: https://github.com/FIWARE/context.Orion-LD/pull/886.
However, this fix may be just temporary - need to hear with my colleagues in ETSI ISG CIM-

What I did was to ignore the user's request of getting "application/ld+json", and instead (as that makes no sense for this request), I return "application/json".
