### ISSUE TITLE
What is the best way to link multiple Orion-LDs?

### ISSUE THREAD

**Issue by ctc-enokida** [Fiware/context.Orion-LD#904]
Hi

We are considering linking multiple Orion-LDs.
Data updates occur in each Orion-LD, and we would like to reflect the updates to each other.

In this case, what is the best way to do so?

I thought that the ”smart federation” feature in the roadmap would do that, but has that been implemented yet?
And is the ”smart federation” feature a realization of SPEC's ”Federated Architecture”?

■RoadMap
　https://github.com/FIWARE/context.Orion-LD/blob/develop/doc/roadmap.md
■Spec
　https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.04.02_60/gs_cim009v010402p.pdf

Thank you so much.

**Comment by kzangeli** [comment]
It's a bit early for the Orion-LD implementation to think about federation, I'm afraid.
Forwarding is being discussed in ETSI ISG CIM (where the NGSI-LD API is defined) but it is still kind of far from being materialized.
To link NGSI-LD brokers you need the forwarding to be first defined and then implemented.

What Orion-LD can offer today is maintaining copies of entities from other brokers, using the /ngsi-ld/ex/v1/notify.
However, this is not NGSI-LD standard (that's why there's an extra "ex" in the path).

Also, we have a forwarding PoC implemented in Orion-LD but it supports only two operations:
* GET /ngsi-ld/v1/entities/{entity-id}
* PATCH /ngsi-ld/v1/entities/{entity-id}/attrs/{attr-name}

That's all we can offer at this stage, sorry
